# Merges coverage data with data from Anvio/EukCC2 pipeline.
using DataFrames, CSV, StringEncodings, CairoMakie, StatsBase
include("functions.jl")
function main()
    covPath = joinpath(@__DIR__, "private/data/prerequisite/coverage/")
    mdPath = joinpath(@__DIR__, "private/data/prerequisite/mergedMAGs.csv")
    completionPath = joinpath(@__DIR__, "private/data/prerequisite/binCompletion.csv")
    coverage = constructDF(covPath)
    filter!([:bin] => filterBins, coverage)
    coverage.sample = formatPIDs(coverage.sample)
    coverage.bin = replace.(coverage.bin, "." => "_")
    rmDuplicatePIDs!(coverage, :sample)
    rmDuplicateBins!(coverage, :bin, mdPath)
    transformedDF = transformDF(coverage)
    completionData = CSV.read(completionPath, DataFrame)
    completionData.bin = rmRunPrefix(completionData.bin)
    outputDf = innerjoin(transformedDF, completionData, on = :bin)
    outPath = joinpath(@__DIR__, "private/", "data/", "outputDB.csv")
    CSV.write(outPath, outputDf)
end
main()